imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

security:
    firewalls:
        operatori:
          http_basic:
            provider: fos_userbundle
    providers:
        in_memory:
            memory:
                users:
                    gpa:
                        password: gpapass
                        roles: 'ROLE_GPA'
                    gpa_no_role:
                        password: gpapass
                        roles: 'ROLE_NOT_GPA'
                    ez:
                        password: ez
                        roles: 'ROLE_EZ'
                    ez_no_role:
                        password: ez
                        roles: 'ROLE_NOT_EZ'
