app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_security:
  resource: "@FOSUserBundle/Resources/config/routing/security.xml"
  prefix: /operatori

fos_profile:
  resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
  prefix: /operatori/profile

fos_resetting:
  resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
  prefix: /operatori/resetting

fos_password:
  resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
  prefix: /operatori/profile
